/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeIdRouteImport } from './routes/knowledge.$id'
import { Route as DefectsNewRouteImport } from './routes/defects.new'
import { Route as DefectsIdRouteImport } from './routes/defects.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIdRoute = KnowledgeIdRouteImport.update({
  id: '/knowledge/$id',
  path: '/knowledge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DefectsNewRoute = DefectsNewRouteImport.update({
  id: '/defects/new',
  path: '/defects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DefectsIdRoute = DefectsIdRouteImport.update({
  id: '/defects/$id',
  path: '/defects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/defects/$id': typeof DefectsIdRoute
  '/defects/new': typeof DefectsNewRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/knowledge/': typeof KnowledgeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/defects/$id': typeof DefectsIdRoute
  '/defects/new': typeof DefectsNewRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/knowledge': typeof KnowledgeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/defects/$id': typeof DefectsIdRoute
  '/defects/new': typeof DefectsNewRoute
  '/knowledge/$id': typeof KnowledgeIdRoute
  '/knowledge/': typeof KnowledgeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/defects/$id'
    | '/defects/new'
    | '/knowledge/$id'
    | '/knowledge/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/defects/$id'
    | '/defects/new'
    | '/knowledge/$id'
    | '/knowledge'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/defects/$id'
    | '/defects/new'
    | '/knowledge/$id'
    | '/knowledge/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DefectsIdRoute: typeof DefectsIdRoute
  DefectsNewRoute: typeof DefectsNewRoute
  KnowledgeIdRoute: typeof KnowledgeIdRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$id': {
      id: '/knowledge/$id'
      path: '/knowledge/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof KnowledgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defects/new': {
      id: '/defects/new'
      path: '/defects/new'
      fullPath: '/defects/new'
      preLoaderRoute: typeof DefectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defects/$id': {
      id: '/defects/$id'
      path: '/defects/$id'
      fullPath: '/defects/$id'
      preLoaderRoute: typeof DefectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DefectsIdRoute: DefectsIdRoute,
  DefectsNewRoute: DefectsNewRoute,
  KnowledgeIdRoute: KnowledgeIdRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
